name: flutter_starter_clean_bloc
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0-312.0.dev

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3
  go_router: ^14.8.0
  internet_connection_checker_plus: ^2.7.0
  intl: ^0.19.0
  logger: ^2.5.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.1
  timeago: ^3.7.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_lints: ^5.0.0
  flutter_lorem: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lang/
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # To add custom fonts to your application, add a fonts section here
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
